services:
  - type: web
    name: tol-sales-dashboard
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sales_v2:server --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: pserv
    name: tol-sales-db
    env: docker
    region: singapore
    plan: free
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
